### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by hozaifajayeb3** [shibajee/realtek-hda-creative-sbc-mod#2]
Hey there, I have been using this mod for 4 months and had 0 issues with it but recently, the app isnt working, it doesnt popup on startup, my windows version got updated to 2004 version so i think that maybe is a issue but i tried re installing before the windows update and it still didnt work. This driver is very good. I really appreciate your work. It would be very helpful if you look into the issue. and 1 more thing, your other driver mods are super good BUT there is one problem that is, when i unplug headphone and re plug it there is no popup of the driver(realtake driver) i have to launch realtake console and connect manually, this is super annoying and sometimes it doesnt even work. It would be really helpful if you fix that on the next updates of other mods(dont worry sbc doesnt have this issue) but yeah, please look into it. love your work and modded drivers.

Thank You

**Comment by Blancpa** [comment]
I got same issue too.Aplication wont start.

**Comment by shibajee** [comment]
Hi, sorry for the late reply. I updated the soft to latest 8967 version which should be compatible with Windows 10 2004. Give it a try and tell me if it's working properly. Uninstall previously installed realtek driver and related soft before u install this. @hozaifajayeb3 @Blancpa

**Comment by Blancpa** [comment]
Thank you so much but I got a new problem with this driver.When i try to install this driver instant blue screen for my every try.System thread exception not handled and RTKVHD64.SYS .

**Comment by shibajee** [comment]
> Thank you so much but I got a new problem with this driver.When i try to install this driver instant blue screen for my every try.System thread exception not handled and RTKVHD64.SYS .

r u on latest windows 10 2004 build ? (Windows Key+R and type > winver and then hit enter) @Blancpa

**Comment by Blancpa** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/61714193/90054825-0fdd3c00-dce5-11ea-97fc-5e08cf5e55a6.JPG)
There are not any update on windows update.

**Comment by shibajee** [comment]
can u do a quick test for me ? I will give u a link of a driver within next 5~6 min..dl it and test it..give me a feedback @Blancpa

**Comment by Blancpa** [comment]
Of course.

**Comment by shibajee** [comment]
> Of course.

https://mega.nz/folder/2UNhySpZ#qrmR9DmBeMocGbfSiCPzYw , just the driver..genkga and creative soft same as before...test it @Blancpa

**Comment by Blancpa** [comment]
I installed driver there is no blue screen anymore but still program not work.

**Comment by shibajee** [comment]
creative program launch properly but u don't get any effect, right ? @Blancpa

**Comment by Blancpa** [comment]
No Program not louch.

**Comment by Blancpa** [comment]
When i try to open program its not open and windows reporting service open in task manager.

**Comment by shibajee** [comment]
> No Program not louch.

ya, windows compatibility issue..this program probably won't work on windows from 2004 update...1909 is the last version @Blancpa ...we have to move on to the UWP version @Blancpa

**Comment by Blancpa** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/61714193/90058520-816bb900-dcea-11ea-8e14-2276748812c9.JPG)
Nahimic mirroring device and audio effect component can cause this?I block this drivers from windows uptade but what ever i did it install itself automaticly after some weeks.

**Comment by shibajee** [comment]
Right click on This PC > properties > advanced system settings > hardware > device installation settings > No, let me choose what to do > never install driver from windows update > ok/apply whatever...uninstall those nahimic component from device manager, both A-volute and mirroring..restart ur PC @Blancpa

**Comment by Blancpa** [comment]
I did it before but it still install after restart pc.
![Ekran Alıntısı](https://user-images.githubusercontent.com/61714193/90060624-ae6d9b00-dced-11ea-93c5-b8f2217b4808.JPG)

**Comment by shibajee** [comment]
Classic windows 10 surprise me everyday. There is a group policy editor hack or registry hack something like that for driver update, search on google. I'm far away from my windows 10 pc, that's why can't help. @Blancpa

**Comment by Blancpa** [comment]
I try it before it wont work on windows home :D.Work on windows pro.Only way disabling this disabling uptades from windows uptade.Microsoft has a tool for it but after some weeks still it install again.

**Comment by hozaifajayeb3** [comment]
Lemme know if you fixed it. thanks

**Comment by shibajee** [comment]
The driver is working fine in my Windows 10 PC (OS Build 19041.508), personally installed and tested it. You guys probably doing something wrong. @hozaifajayeb3 @Blancpa

**Comment by hozaifajayeb3** [comment]
I dont know, I followed every steps and didnt work even tho I have USB Headphones now.

**Comment by hozaifajayeb3** [comment]
another thing, will this work on USB headphones tho? As realtek doesn't detect USB inputs

**Comment by shibajee** [comment]
nope it won't, realtek won't detect any usb input @hozaifajayeb3
